/**
 * Typed mock seam for the Legal page editor. Mirrors the data shown in
 * mockups/tadaify-mvp/app-page-legal.html so the screen graduates by swapping
 * this factory for the real loader. A Legal page is a multi-policy single page —
 * Terms / Privacy / Cookie / Refund / DMCA / Accessibility / AUP — each policy
 * rendering as its own section with version tracking on the public page.
 *
 * All starter body text is mockup-only PLACEHOLDER content; production carries
 * its own disclaimer + jurisdiction selection.
 *
 * @implements fr-page-editor-legal
 */
export type LegalPolicy = {
  id: string;
  icon: string;
  name: string;
  version: string;
  effective: string;
  updated: string;
  /** Optional extra chip after the meta line (e.g. "GDPR variant"). */
  variant?: string;
  anchor: string;
  pastVersions: number;
  collapsed?: boolean;
  /** Body markdown (only present for expanded policies in the fixture). */
  body?: string;
  /** Auto-generated TOC entries shown under the body. */
  toc?: { num: string; text: string }[];
  /** Inline tier hint shown in the (collapsed) body. */
  tierHint?: string;
};

export type LegalPolicyType = {
  type: string;
  icon: string;
  name: string;
  sub: string;
  added?: boolean;
  badge?: "creator" | "pro" | "business";
};

export type LegalTemplate = {
  id: string;
  emoji: string;
  name: string;
  sub: string;
  bullets: string[];
};

export type LegalChecklistItem = {
  state: "met" | "needed" | "na";
  name: string;
  sub: string;
};

export type LegalTranslation = { flag: string; name: string; done: boolean };

export type LegalVersionRow = {
  version: string;
  effective: string;
  changes: string;
  current?: boolean;
};

export type LegalFixture = {
  pageTitle: string;
  slug: string;
  live: boolean;
  footerLink: boolean;
  noindex: boolean;
  backgrounds: { name: string; css: string }[];
  selectedBackground: number;
  seo: { title: string; description: string };
  titleAlts: { title: string; slug: string }[];
  policies: LegalPolicy[];
  policyTypes: LegalPolicyType[];
  templates: LegalTemplate[];
  checklist: LegalChecklistItem[];
  review: { lastReviewed: string; dueBy: string };
  translations: LegalTranslation[];
  versionHistory: LegalVersionRow[];
};

const TERMS_BODY = `## 1. Acceptance of terms

By accessing strongnotskinny.com (the "Site") and any products or services we offer, you agree to be bound by these Terms of Service.

## 2. Eligibility

You must be at least 18 years old, or the age of majority in your jurisdiction, to purchase services or products from us.

## 3. Subscriptions and payments

Coaching subscriptions auto-renew monthly. You may cancel at any time from your account dashboard; cancellation takes effect at the end of the current billing period.

## 4. Intellectual property

All training plans, video content, and written materials are owned by Alexandra Silva and may not be redistributed, resold, or reproduced without written permission.

## 5. Disclaimer of warranties

Our content is for informational and educational purposes only and is not medical advice. Consult a qualified healthcare provider before starting any new fitness program.

## 6. Limitation of liability

To the maximum extent permitted by law, our total liability for any claim arising from your use of the Site is limited to the amount you paid us in the 12 months preceding the claim.

## 7. Governing law

These Terms are governed by the laws of England and Wales. Any dispute will be resolved in the courts of London, United Kingdom.`;

const PRIVACY_BODY = `## 1. What we collect

We collect personal data you give us directly (name, email, billing address) and data automatically generated by your use of the Site (IP address, device type, pages visited, time on page).

## 2. Why we collect it (legal basis under GDPR Art. 6)

- Performance of contract — to deliver the products and coaching you've purchased.
- Legitimate interest — to keep the Site secure and improve our services.
- Consent — for marketing emails and non-essential cookies.

## 3. How long we keep it

Account data: as long as your account is active, plus 7 years for tax purposes after account closure (UK requirement). Anonymised analytics: 26 months.

## 4. Your rights

Under GDPR you have the right to access, rectify, erase, restrict processing of, port, and object to processing of your personal data.

## 5. International transfers

Some of our processors (Stripe, Google Workspace, Cloudflare) are based in the United States. Where data leaves the EU/UK, we rely on Standard Contractual Clauses (SCCs).

## 6. Data Protection Officer

We are not legally required to appoint a DPO, but data protection inquiries are handled by Alexandra Silva personally.`;

export const legalEditorFixture = (): LegalFixture => ({
  pageTitle: "Legal",
  slug: "legal",
  live: true,
  footerLink: true,
  noindex: true,
  backgrounds: [
    { name: "Inherit theme", css: "var(--bg)" },
    { name: "White (best for readability)", css: "#FFFFFF" },
    { name: "Warm cream", css: "#F8F4EE" },
    { name: "Cool grey", css: "#F9FAFB" },
    { name: "Slate", css: "#1F2937" },
    { name: "Dark canvas", css: "#0B0F1E" },
  ],
  selectedBackground: 0,
  seo: {
    title: "Legal — Strong Not Skinny by Alexandra Silva",
    description:
      "Terms of Service, Privacy Policy, Refund Policy, and Cookie Policy for Strong Not Skinny products and coaching.",
  },
  titleAlts: [
    { title: "Legal", slug: "legal" },
    { title: "Policies", slug: "policies" },
    { title: "Terms & Privacy", slug: "terms" },
    { title: "Legal Center", slug: "legal-center" },
  ],
  policies: [
    {
      id: "terms",
      icon: "📜",
      name: "Terms of Service",
      version: "1.2",
      effective: "2026-04-01",
      updated: "2026-03-28",
      anchor: "#terms",
      pastVersions: 3,
      body: TERMS_BODY,
      toc: [
        { num: "§ 1", text: "Acceptance of terms" },
        { num: "§ 2", text: "Eligibility" },
        { num: "§ 3", text: "Subscriptions and payments" },
        { num: "§ 4", text: "Intellectual property" },
        { num: "§ 5", text: "Disclaimer of warranties" },
        { num: "§ 6", text: "Limitation of liability" },
        { num: "§ 7", text: "Governing law" },
      ],
    },
    {
      id: "privacy",
      icon: "🔒",
      name: "Privacy Policy",
      version: "2.0",
      effective: "2026-04-15",
      updated: "2026-04-15",
      variant: "GDPR variant",
      anchor: "#privacy",
      pastVersions: 2,
      body: PRIVACY_BODY,
    },
    { id: "cookie", icon: "🍪", name: "Cookie Policy", version: "1.0", effective: "2026-03-01", updated: "2026-03-01", anchor: "#cookie", pastVersions: 0, collapsed: true },
    { id: "refund", icon: "💸", name: "Refund Policy", version: "1.1", effective: "2026-04-01", updated: "2026-04-01", anchor: "#refund", pastVersions: 0, collapsed: true },
    {
      id: "dmca",
      icon: "©️",
      name: "DMCA / Copyright Policy",
      version: "1.0",
      effective: "2026-03-15",
      updated: "2026-03-15",
      anchor: "#dmca",
      pastVersions: 0,
      collapsed: true,
      tierHint: "DMCA Policy is part of Creator. Recommended if you host user-submitted content (comments, contact-form attachments, community submissions).",
    },
  ],
  policyTypes: [
    { type: "terms", icon: "📜", name: "Terms of Service", sub: "Conditions for using your site, products, services.", added: true },
    { type: "privacy", icon: "🔒", name: "Privacy Policy", sub: "What data you collect, why, how long you keep it.", added: true },
    { type: "cookie", icon: "🍪", name: "Cookie Policy", sub: "Cookies you set + opt-out instructions.", added: true },
    { type: "refund", icon: "💸", name: "Refund Policy", sub: "Refund window, eligibility, how to request.", added: true },
    { type: "dmca", icon: "©️", name: "DMCA / Copyright Policy", sub: "For sites with user-generated content.", added: true },
    { type: "accessibility", icon: "♿", name: "Accessibility Statement", sub: "Required by some EU/US jurisdictions for businesses.", badge: "creator" },
    { type: "aup", icon: "🤝", name: "Acceptable Use Policy", sub: "Rules for community / team / commenter behaviour.", badge: "creator" },
    { type: "imprint", icon: "🏛️", name: "Imprint / Impressum", sub: "Required for German + Austrian businesses (Telemediengesetz §5)." },
    { type: "custom", icon: "📄", name: "Custom policy", sub: 'Blank — name it yourself (e.g. "Affiliate disclosure").' },
  ],
  templates: [
    { id: "tos-generic", emoji: "📜", name: "Generic Terms of Service", sub: "Works for most creators selling digital products, courses, services, or coaching.", bullets: ["7 sections (Acceptance / Eligibility / Payments / IP / Disclaimer / Liability / Governing law)", "~1,200 words · ~5 min read", "UK / generic-EN governing law (editable)"] },
    { id: "privacy-gdpr", emoji: "🔒", name: "Privacy Policy (GDPR)", sub: "EU-friendly default. Covers Art. 6 legal bases, retention, data subject rights, international transfers.", bullets: ["6 sections + DPO section", "~1,500 words", "SCC clause for US processors"] },
    { id: "privacy-ccpa", emoji: "🇺🇸", name: "Privacy Policy (US-only)", sub: "CCPA / CPRA-friendly for California residents. Lighter than GDPR but still covers 'Do Not Sell'.", bullets: ["5 sections", "~900 words", "Includes 'Do Not Sell My Personal Info' section"] },
    { id: "cookie", emoji: "🍪", name: "Cookie Policy", sub: "Explains the cookies your site sets (Stripe, Google Analytics, tadaify session) + opt-out instructions.", bullets: ["3 sections + per-cookie table", "~600 words", "Pre-fills cookies based on integrations you've enabled"] },
    { id: "refund-digital", emoji: "💸", name: "Refund Policy — Digital products", sub: "14-day money-back guarantee for digital downloads / courses (matches EU Distance Selling defaults).", bullets: ["4 sections", "~500 words", "Sister templates: Physical / Service / Subscription"] },
    { id: "dmca", emoji: "©️", name: "DMCA Counter-notice", sub: "For sites that host visitor-submitted content (comments, contact form attachments). Includes designated agent fields.", bullets: ["5 sections + agent contact block", "~800 words", "17 USC §512 safe-harbor compliant"] },
  ],
  checklist: [
    { state: "met", name: "Terms of Service", sub: "You're selling 3 products via Stripe." },
    { state: "met", name: "Privacy Policy (GDPR)", sub: "EU visitors detected (38% of traffic)." },
    { state: "met", name: "Refund Policy", sub: "Required by Stripe for paid offers." },
    { state: "needed", name: "Cookie Policy", sub: "You use Google Analytics — add a Cookie Policy + consent banner." },
    { state: "met", name: "DMCA Counter-notice", sub: "Your contact form accepts attachments." },
    { state: "na", name: "Accessibility Statement", sub: "Optional — required by some EU/US jurisdictions for businesses." },
  ],
  review: { lastReviewed: "Apr 1, 2026", dueBy: "Apr 1, 2027" },
  translations: [
    { flag: "🇬🇧", name: "English (default)", done: true },
    { flag: "🇵🇱", name: "Polski", done: false },
    { flag: "🇩🇪", name: "Deutsch", done: false },
    { flag: "🇪🇸", name: "Español", done: false },
  ],
  versionHistory: [
    { version: "v1.2", effective: "Effective Apr 1, 2026 (current)", changes: "Tightened cancellation language · Added jurisdiction clarification for non-UK customers · Updated contact email.", current: true },
    { version: "v1.1", effective: "Effective Jan 15, 2026", changes: "Added subscription auto-renewal language for Coaching Plus tier · Clarified IP ownership for downloadable PDFs." },
    { version: "v1.0", effective: "Effective Sep 1, 2025", changes: "Initial publication. Based on Generic ToS template, customised for fitness coaching business." },
  ],
});
